version: "3"
services:
  test:
    build:
      context: .
    volumes:
      - ./:/app:ro
    working_dir: /app
    depends_on:
      - postgres
    command:
      [
        "python3",
        "-m",
        "unittest",
        "tests/test_client.py",
      ]
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
