version: "3"
services:
  test:
    build:
      context: .
    volumes:
      - ./:/app:ro
    working_dir: /app
    command:
      [
        "python3",
        "-m",
        "unittest",
        "tests/test_client_caches.py",
        "tests/test_client_positions.py",
      ]
